import os

with open("src-tauri/src/database.rs", "a", encoding="utf-8") as f:
    f.write("\n")
    f.write("async fn migration_008_fix_missing_columns(pool: &sqlx::SqlitePool) -> Result<(), String> {\n")
    f.write("    if !column_exists(pool, \"categories\", \"parent_id\").await? {\n")
    f.write("        sqlx::query(\"ALTER TABLE categories ADD COLUMN parent_id INTEGER\").execute(pool).await.map_err(|e| e.to_string())?;\n")
    f.write("    }\n")
    f.write("    if !column_exists(pool, \"categories\", \"flavor\").await? {\n")
    f.write("        sqlx::query(\"ALTER TABLE categories ADD COLUMN flavor TEXT\").execute(pool).await.map_err(|e| e.to_string())?;\n")
    f.write("    }\n")
    f.write("    if !column_exists(pool, \"categories\", \"margin_target\").await? {\n")
    f.write("        sqlx::query(\"ALTER TABLE categories ADD COLUMN margin_target REAL\").execute(pool).await.map_err(|e| e.to_string())?;\n")
    f.write("    }\n")
    f.write("    if !column_exists(pool, \"areas\", \"active\").await? {\n")
    f.write("        sqlx::query(\"ALTER TABLE areas ADD COLUMN active INTEGER DEFAULT 1\").execute(pool).await.map_err(|e| e.to_string())?;\n")
    f.write("    }\n")
    f.write("    if !column_exists(pool, \"areas\", \"account_count\").await? {\n")
    f.write("        sqlx::query(\"ALTER TABLE areas ADD COLUMN account_count INTEGER DEFAULT 0\").execute(pool).await.map_err(|e| e.to_string())?;\n")
    f.write("    }\n")
    f.write("    if !column_exists(pool, \"invoices\", \"amount_paid\").await? {\n")
    f.write("        sqlx::query(\"ALTER TABLE invoices ADD COLUMN amount_paid REAL DEFAULT 0.0\").execute(pool).await.map_err(|e| e.to_string())?;\n")
    f.write("    }\n")
    f.write("    if !column_exists(pool, \"accounts\", \"salary\").await? {\n")
    f.write("        sqlx::query(\"ALTER TABLE accounts ADD COLUMN salary REAL DEFAULT 0.0\").execute(pool).await.map_err(|e| e.to_string())?;\n")
    f.write("    }\n")
    f.write("    if !column_exists(pool, \"accounts\", \"details\").await? {\n")
    f.write("        sqlx::query(\"ALTER TABLE accounts ADD COLUMN details TEXT\").execute(pool).await.map_err(|e| e.to_string())?;\n")
    f.write("    }\n")
    f.write("    if !column_exists(pool, \"accounts\", \"status\").await? {\n")
    f.write("        sqlx::query(\"ALTER TABLE accounts ADD COLUMN status TEXT DEFAULT 'ACTIVE'\").execute(pool).await.map_err(|e| e.to_string())?;\n")
    f.write("    }\n")
    f.write("    Ok(())\n")
    f.write("}\n")
